---

- name: Instalando gpg
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Adicionando gpg key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no

- name: Adicionando o repositorio do Grafana
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no

- name: Instalando o grafana via gerenciador de pacotes apt
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Iniciando o servico grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Esperando o servico do grafana terminar de levantar
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: Alterando a senha do usuario admin do grafana para a gui
  command : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0

- name: Create API key
  uri:
    url: http://localhost:3000/api/auth/keys
    user: "admin"
    password: "admin"
    force_basic_auth: true
    method: POST
    body_format: json
    body: >
      {
        "name": "ansible",
        "role": "Admin"
      }
  #no_log: true
  register: grafana_api_key
  tags: apikey

- name: Create prometheus datasource
  community.grafana.grafana_datasource:
    name: Prometheus
    url: http://localhost:3000
    grafana_api_key: "{{ grafana_api_key.json.key }}"
    ds_type: prometheus
    ds_url: http://localhost:9090

- name: Create NGINX dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_api_key: "{{ grafana_api_key.json.key }}"
    commit_message: Updated by Ansible
    overwrite: yes
    dashboard_url: https://raw.githubusercontent.com/nginxinc/nginx-prometheus-exporter/v0.11.0/grafana/dashboard.json
  tags: dashboard

- name: Create node exporter full dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_api_key: "{{ grafana_api_key.json.key }}"
    commit_message: Updated by Ansible
    overwrite: yes
    dashboard_url: https://raw.githubusercontent.com/rfmoz/grafana-dashboards/master/prometheus/node-exporter-full.json
  tags: dashboard