---

  - name: Instalando o Nginx e PHP para o funcionamento do Wordpress
    apt:
      pkg:
      - nginx
      - unzip
      - php7.4-zip
      - php-imagick
      - php7.4-curl
      - php7.4-fpm
      - php7.4-mbstring
      - php7.4-cli
      - php7.4-bcmath
      - php7.4-xml
      - php7.4-mysql
      - php7.4-common
      - php7.4-gd
      - php7.4-json
      - php7.4-intl
      - php7.4-soap
      - php7.4-xmlrpc
      - mysql-client
      - python3-mysqldb
      - libmysqlclient-dev
      - nfs-common
      - memcached
      - php-memcached
      update_cache: yes
      state: present
  
  - name: Configurando vhost Nginx
    copy:
      src: vhost.nginx.conf
      dest: /etc/nginx/sites-enabled/default 
  
  - name : Baixando o projeto do Wordpress e descompactando 
    ansible.builtin.unarchive:
      src: https://wordpress.org/latest.zip
      dest: /var/www/html
      remote_src: yes

  - name: Alterando o arquivo wp-config
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php
  
  - name: Alterando permissão da pasta /var/www/html/wordpress
    ansible.builtin.file:
      path: /var/www/html/wordpress
      owner: www-data
      group: www-data
      mode: '0755'
      recurse: yes

  - name: Criando diretorio de uploads dentro do projeto Wordpress
    ansible.builtin.file:
      path: /var/www/html/wordpress/wp-content/uploads
      state: directory
      mode: '0755'

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /var/www/html/wordpress/wp-content/uploads
      dest: /uploads
      owner: www-data
      group: www-data
      mode: '0755'
      state: link

  - name: Definindo a montagem do storage EFS em auto inicializacao mapeando para o diretório upload
    ansible.builtin.lineinfile:
      path: /etc/fstab
      state: present
      line: '{{ file_system_id }}.efs.{{ aws_region }}.amazonaws.com:/ /uploads nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev 0 0'
  
  - name: Alterando o arquivo php.ini
    template:
      src: php.ini.j2
      dest: /etc/php/7.4/cli/php.ini

  - name: Criando diretorio ssls dentro do diretório do Nginx
    ansible.builtin.file:
      path: /etc/nginx/ssls
      state: directory
  
  - name: Copiando o arquivo certificate.crt para o diretorio ssls do Nginx
    copy:
      src: files/certificate.crt
      dest: /etc/nginx/ssls/
  
  - name: Copiando o arquivo private.pem para o diretorio ssls do Nginx
    copy:
      src: files/private.pem
      dest: /etc/nginx/ssls/

  - name: Copiando o arquivo phpinfo.php para o diretorio raiz do wordpress
    copy:
      src: files/phpinfo.php
      dest: /var/www/html/wordpress/

  - name: Reiniciando o Nginx
    service:
      name: nginx
      state: restarted

  - name: Reiniciando o php7.4-fpm
    service:
      name: php7.4-fpm
      state: restarted