---

- name: Checando se o node exporter ja existe
  stat:
    path: "{{ node_exporter_bin }}"
  register: __check_node_exporter_present
  
- name: Criando o usuario do node exporter
  user:
    name: "{{ node_exporter_user }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: Criando o diretorio de configuracao do node exporter
  file:
    path: "{{ node_exporter_dir_conf }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    
- name: Se o node exporter existir pegar versao
  shell: "cat /etc/systemd/system/node_exporter.service | grep Version | sed s/'.*Version '//g"
  when: __check_node_exporter_present.stat.exists == true
  changed_when: false
  register: __get_node_exporter_version
  
- name: Baixando e descompactando o node exporter se ele ainda nao existir
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    validate_certs: no
    
- name: Movendo o binario para o destino final
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_bin }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0755
    remote_src: yes
  when: __check_node_exporter_present.stat.exists == false or not __get_node_exporter_version.stdout == node_exporter_version
  
- name: Limpando o lixo do diretorio tmp
  file:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/
    state: absent
    
- name: Instalando o servico do node exporter na maquina
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_node_exporter
  
- meta: flush_handlers
  
- name: Garantindo o estado started do servico do node exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes

- name: Checando se o servico do node exporter esta emitindo as metricas
  uri:
    url: http://127.0.0.1:9100/metrics
    method: GET
    status_code: 200