---

- name: Atualizando e instalando o Prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Copiando o arquivo de argumentos do Prometheus
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus

- name: Copiando o arquivo de configuracao do Prometheus para dentro do servidor
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus

- name: Iniciando o servico do Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes