---

- name: Reiniciando o servico do Prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: restart_prometheus

- name: Recarregando o servico do Prometheus
  uri:
    url: http://localhost:9090/-/reload
    method: POST
    status_code: 200
  listen: reload_prometheus